media:
  input: ./        # Saves images in the same folder as the .md file being edited
  output: ./       # Inserts relative links like ./diagram.png
content:
  - name: docs
    label: Documentation
    type: collection
    path: docs # or path where your .md files live
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
