# Media configuration allowing you to browse/upload across your media folders
media:
  - name: docs_media
    label: Media
    input: docs/media
    output: /

# Content Collections
content:
  - name: docs
    label: All Documentation
    type: collection
    path: docs
    exclude:
      - "**/media/**"
      - "**/images/**"
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Page Content
        type: rich-text
